//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembersPRO.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestJsonData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestJsonData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MembersPRO.Tests.TestJsonData", typeof(TestJsonData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;This&quot;: &quot;should fail\&quot;}.
        /// </summary>
        internal static string JsonToFail {
            get {
                return ResourceManager.GetString("JsonToFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:&quot;2.22.3&quot;,&quot;time&quot;:1613471591,&quot;blocks&quot;:[{&quot;id&quot;:&quot;123456abcdef&quot;,&quot;type&quot;:&quot;header&quot;,&quot;data&quot;:{&quot;level&quot;:1,&quot;text&quot;:&quot;We Do One Thing, &amp; One Thing Well&quot;,&quot;alignment&quot;:&quot;center&quot;}},{&quot;id&quot;:&quot;123456abcdef&quot;,&quot;type&quot;:&quot;header&quot;,&quot;data&quot;:{&quot;level&quot;:1,&quot;text&quot;:&quot;(MembersPRO is &lt;font color=\&quot;red\&quot;&gt;&lt;u&gt;not an all-in-one platform&lt;/u&gt;&lt;/font&gt;, and we don&apos;t try to be)&quot;,&quot;alignment&quot;:&quot;center&quot;}},{&quot;id&quot;:&quot;123456abcdef&quot;,&quot;type&quot;:&quot;paragraph&quot;,&quot;data&quot;:{&quot;text&quot;:&quot;Most all-in-one platforms have a ton of things to offer, however, they often lack quality in any on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonToPass {
            get {
                return ResourceManager.GetString("JsonToPass", resourceCulture);
            }
        }
    }
}
